package Classes;

public interface AnonymousClass2 {
	public void eat();
}
class InnerClass2{
	public static void main(String[] args) {
		AnonymousClass2 a2=new AnonymousClass2(){
			public void eat(){
				System.out.println("Fruit");
			}
		};
		a2.eat();
		//Internal Class Generated by Compiler
				/*
				 *  static class InnerClass2$1 implements InnerClass2{
				 *  	InnerClass2$1(){}
				 *      void eat(){
				 *      	System.out.println("Fruits");
				 *      }
				 *  }
				 */
				//this class is referenced by variable e
	}
}
