package Classes;

abstract class AnonymousClassMain {
	abstract void eat();
}
class InnerClass{
	public static void main(String[] args) {
		AnonymousClassMain a=new AnonymousClassMain(){
			void eat(){
				System.out.println("Fruit");
			}
		};
		a.eat();
		//Internal Class Generated by Compiler
				/*
				 *  static class InnerClass$1 extends InnerClass{
				 *  	InnerClass$1(){}
				 *      void eat(){
				 *      	System.out.println("Fruits");
				 *      }
				 *  }
				 */
				//this class is referenced by variable a
		
	}
}
